### ISSUE TITLE
Cannot find the PVP BGM 'Blood for blood'

### ISSUE THREAD

**Issue by shaka0919** [lmcintyre/OrchestrionPlugin#10]
blood for blood is a BGM of PVP Frontlines and mentioned in the description Rouse out 'Transition of blood for blood'
https://www.youtube.com/watch?v=0sHf9qq82eU
but I cannot find this BGM in the list. not sure the name is different with in game showing.

**Comment by lmcintyre** [comment]
This BGM will play when the Orchestrion plugin is playing Rouse Out and you enter combat with the special mode setting enabled in Orchestrion's settings.
