### ISSUE TITLE
Display name in other language

### ISSUE THREAD

**Issue by Civciv546** [lmcintyre/OrchestrionPlugin#13]
I apologize for my poor English.

I would like to see song titles in other languages (I prefer Japanese) as well as English names!
I can add Japanese titles to the list in ffxiv_bgm.csv, so can you add the feature to display them in another language?

**Comment by MisaUo** [comment]
Thank you for creating the powerful plugin.
I have created a Japanese version of ffxiv_bgm.csv. If you would like to create a Japanese version, I hope this can be helpful to you!
https://docs.google.com/spreadsheets/d/1TPe0BXlzjoAVHXrSLc3ZmsaIXerdIyAWADkd8YY_W8A/
