### ISSUE TITLE
[Feature Request] Add "Keep Previous Song" to the top of Replacement Song dropdown

### ISSUE THREAD

**Issue by ryankhart** [lmcintyre/OrchestrionPlugin#14]
I just thought of a feature that I'd find quite welcome. I like a majority of the music in this game, but fate music is not music that I want to hear, particularly, if I'm just passing through and have no intention of sticking around in the fates.

Currently, I can replace various fate songs with "None" but that would just stop the chill song that's currently playing.

I don't know how feasible it is to catch the game before I ends the previous song to stop it from fading out. I suspect that that is that hardest part of adding this feature.

So, like the title suggests, maybe a "Keep Previous Song" option could be prepended to the top of the "Replacement Song" dropdown on the Replacements tab.

**Comment by lmcintyre** [comment]
This is what the option "Do not change BGM" does. Do you have a suggestion for re-wording that would make this clearer?

**Comment by ryankhart** [comment]
OH! Wow, I didn't realize that was an option. I thought it was just placeholder text because it was the default.

To me, "Do not change BGM" meant do not change the target song. Maybe changing it to "Keep playing previous BGM" would be clearer? I just tested it out, and it seems to do exactly as I was requesting in this issue.

**Comment by lmcintyre** [comment]
Yeah I can definitely see how that would be confusing. I'll think of a better way to word it for next version. Thanks for the issue 🙂
