### ISSUE TITLE
Missing Song: The Twin Faces of Fate - The Theme of Ul'dah

### ISSUE THREAD

**Issue by HighPrincessErinys** [lmcintyre/OrchestrionPlugin#15]
This song IS present in the game, and has it's own obtainable orchestrion roll (https://ffxiv.consolegameswiki.com/wiki/The_Twin_Faces_of_Fate_-_The_Theme_of_Ul%27dah_Orchestrion_Roll), but is missing from the plugin and the spreadsheet. 

please im begging you fix!!! before i cry about it!!!

**Comment by lmcintyre** [comment]
This plugin does not play orchestrion rolls. The functionality will not be added.
