### ISSUE TITLE
Option to change from dalamud chat type to echo?

### ISSUE THREAD

**Issue by Electrized** [lmcintyre/OrchestrionPlugin#16]
Commit 523f73d changes Orchestrion's text message behavior from echo to dalamud chat.

Is it possible to add an option to change the behavior back to echo? Or alternatively, choose chat channel to print to

The main chat channel being spammed by the dungeon ost changing to the battle ost gets annoying after a while

**Comment by lmcintyre** [comment]
I swapped the chat channel to Dalamud's specified chat channel because it's configurable in Dalamud by default. Just change your Dalamud chat output to Echo in /xlsettings.
