### ISSUE TITLE
Orchestrion Titles Not Updating Inside Housing

### ISSUE THREAD

**Issue by Zynyx** [lmcintyre/OrchestrionPlugin#18]
Hello,

Whenever I'm inside my FC house or my personal, Orchestrion is stuck on "Where the Heart is- 186"

I know it did not used to do this. Is this a known bug or perhaps an issue on my end?

**Comment by lmcintyre** [comment]
Hi! This behavior has never changed. The Orchestrion plugin has never handled Orchestrion (furnishing) tracks, whether playing or detecting which one is playing. The game itself puts the current Orchestrion (furnishing) track into chat.
