### ISSUE TITLE
Orchestrion in CN server doesnt show music in 6.0/6.1 after patch 6.1 released

### ISSUE THREAD

**Issue by zzjjss1** [lmcintyre/OrchestrionPlugin#21]
Before patch 6.1 released , it still had music in 6.0. But after 6.1 released, music in 6.0 was missing.

**Comment by lmcintyre** [comment]
Hi, CN server is not explicitly supported. I don't have the means to test on it so the fact that the plugin worked is coincidental. If someone on CN wants to fix it, forking is fine.
