### ISSUE TITLE
[Feature Request] The option to change the replacement song for existing replacements

### ISSUE THREAD

**Issue by WesselKuipers** [lmcintyre/OrchestrionPlugin#26]
Hi! Love the plugin.

I've been using the replacements feature to replace the music in front of my FC's house since everyone chills out there, but eventually the music in there gets a bit tiring.

When I want to change things up the current workflow would involve deleting the existing replacement, trying to remember the song ID of the original song, then scrolling down to that ID and picking it, then selecting the new song and confirming it.

I think this could be improved in two ways:
- Allowing the user to type in the song selection dropdown to search/filter the list of songs instead of the search bar at the top
- Allowing the user to change an already replaced song in-place, maybe through a pop-up or something?

I wouldn't mind tackling this myself.

**Comment by lmcintyre** [comment]
Thanks for the suggestion. A simple edit button has been added in the latest update. I'm looking to expand upon this UI over time.
