### ISSUE TITLE
Estate Tracks not being recognised.

### ISSUE THREAD

**Issue by elshandra** [lmcintyre/OrchestrionPlugin#27]
Orchestrions are not being updated when entering/leaving private estates (fc estates, apartments, etc.). Nor when track being played changes.

Does not seem to matter if you own the house or not.

Eg: Teleport to Mist, enter a house. Regardless of what music is playing in the house, the porch will just show Where the Heart(h) Is.

**Comment by lmcintyre** [comment]
Orchestrion does not interact with the in-game orchestrion in any way. Sorry for the confusion.

**Comment by elshandra** [comment]
Does it need to interact with the orchestrion to update and maintain the history of songs (systemically) played through the orchestrion? Being able to name the track people have playing in their estates is the one time the "What's Playing/What has Played" feature is really useful. Will you not at least consider?

**Comment by lmcintyre** [comment]
This isn't a "reconsider" issue. I would love to support this functionality, but I don't have time or the skill for the reverse engineering required to determine the current Orchestrion furnishing song. I expect to be able to implement it some day, but definitely not any time soon.

**Comment by elshandra** [comment]
Ah I see, I was hoping that the plugin was Identifying the orchestrion from memory (the in game BGM being loaded). I guess it's just a lookup based on the area/time or smth. 

Also, I'm an idiot you already answered this before.. I forgot to check closed. Sorry!

**Comment by lmcintyre** [comment]
It does identify the playing track from memory. The BGM system is completely separate from the Orchestrion furnishing system, and uses completely different memory structures in completely different locations.
