### ISSUE TITLE
BGM not persisting into estates where orchestrions are present.

### ISSUE THREAD

**Issue by elshandra** [lmcintyre/OrchestrionPlugin#28]
If you use OrchestrionPlugin to set your own BGM, and enter somebody's estate where they have music playing via an orchestrion, the music that will play, will be the Estate's music, rather than the plugins.

The same behaviour happens if you enter an estate with orchestrion-played music, and try to use /porch to play a track.

Expected behaviour is that the BGM should be overridden by OrchestrionPlugin.

**Comment by lmcintyre** [comment]
The Orchestrion furnishing system is intended to override the game's BGM system so that's why the plugin cannot override BGM tracks. This is intended at the moment, but hopefully will be possible to work around in the future.

**Comment by elshandra** [comment]
Yeah, I'm wondering if the key is somewhere in those unknown vars. I would think ultimately, music played by the orchestrion ends up in the same BGM handler. I can appreciate the effort involved to make it work, glad to know it's on the radar at least.
