### ISSUE TITLE
Toggle for "now playing" messages in game chat in all tabs

### ISSUE THREAD

**Issue by Braelisto** [lmcintyre/OrchestrionPlugin#31]
This message shows up in all chat tabs. Not sure if the announcement category for current orchestration track messages could be used to make this toggle-able to a certain chat tab only). It spams the main channel but it's nice to know what's playing when i can't access the dropdown menu (as in, in a cutscene)

**Comment by lmcintyre** [comment]
Hi, Orchestrion outputs to the Dalamud chat channel configured in
/xlsettings.

**Comment by Braelisto** [comment]
Oh thank you so much for this information. I was able to move it to one of my empty linkshell chats. now I can toggle it to just one chat tab. Appreciate the promptness!
