### ISSUE TITLE
opt out for all track manipulation options, only to show ingame bgm

### ISSUE THREAD

**Issue by fuckingwhydude** [lmcintyre/OrchestrionPlugin#32]
constantly tracks loop awkwardly and non fitting tracks on instance/duty's end bleed into following cutscenes (either Victory! or zone music of where you would load out to after exiting duty, perhaps not sure)

**Comment by lmcintyre** [comment]
Do you have the Sound Filter plugin installed?

**Comment by fuckingwhydude** [comment]
nope

**Comment by lmcintyre** [comment]
Huh, the plugin does not do anything at all except tracking the BGM if you do not have any replacements. If you open the Orchestrion settings, do you have the red warning text?
