### ISSUE TITLE
Allow changing which chat channels the plugin sends "now playing" messages in

### ISSUE THREAD

**Issue by anamayagarodia** [lmcintyre/OrchestrionPlugin#35]
I like the feature where the plugin sends "now playing" however, it currently sends it to every chat channel - general, battle, event and a custom FC one I have. I would like it to only send to the general channel.

**Comment by anamayagarodia** [comment]
I haven't really looked into developing dalamud plugins too much yet, and I'm not sure why this particular chat type is used but I believe changing `DalamudApi.PluginInterface.GeneralChatType,` line 123 in `Orchestrion/OrchestrionPlugin.cs` to `Dalamud.Game.Text.XivChatType.SystemMessage,` might help make it filterable by the default XIV client chat log settings. However, I am not sure if `PluginInterface.GeneralChatType` is being used for a specific purpose and if using `SystemMessage` might break that.

Thanks! :D

**Comment by lmcintyre** [comment]
You can change the chat channel that messages go into by changing the
Dalamud chat channel setting in /xlsettings.

I am probably going to separate this out eventually so they can be distinct
settings.

**Comment by lmcintyre** [comment]
Hi! Sorry for leaving this hanging for so long. The update to Orchestrion with patch 6.5 will add the ability to sync the chat channel to the Dalamud setting, or set it separately.
