### ISSUE TITLE
missing song that's an orchestrion roll

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [lmcintyre/OrchestrionPlugin#37]
Navigator’s Glory - The Theme of Limsa Lominsa orchestrion roll seems to be missing from the orchestrion player? Unless it's under some other name.

**Comment by lmcintyre** [comment]
Sorry, the plugin does not play Orchestrion rolls. It plays BGM tracks. That track is not available as BGM, only as an Orchestrion roll, so it cannot be played.

**Comment by RealHypnoticOcelot** [comment]
Is this a planned feature for the future?

**Comment by lmcintyre** [comment]
Not likely. The Orchestrion system is completely distinct from the BGM system, and would require almost a complete rewrite and weeks of reverse engineering in order to do this. As I've just rewritten the plugin a month or two ago, I am not interested in doing that at the moment.

**Comment by RealHypnoticOcelot** [comment]
Alright, thank you!
