### ISSUE TITLE
Older orchestrion rolls missing?

### ISSUE THREAD

**Issue by OnionKnight14** [lmcintyre/OrchestrionPlugin#41]
The 1.0 versions of the town themes aren't on the spreadsheet and don't show up on the plugin. They were added as orchestrion rolls in 4.05. They're called "The Twin Faces of Fate - The Theme of Ul'dah", "Born of the Boughs - The Theme of Gridania" and "Navigator's Glory - The Theme of Limsa Lominsa".

**Comment by lmcintyre** [comment]
The Orchestrion Plugin does not play Orchestrion tracks. There is no way
for me to get the plugin to play those tracks from the game.
