### ISSUE TITLE
[Request] Search bar to filter Replacements

### ISSUE THREAD

**Issue by Almagests** [lmcintyre/OrchestrionPlugin#43]
I have around 100+ replacements created and they're sorted by creation order. It's easy to get lost in such a long list, so I ask if it's possible to create a Search bar to filter Replacements so it's easier to find a replacement that has already been created. I think searching for a bgm and displaying all replacements that it appears (either replacing or being replaced by something else) would be really cool.

**Comment by lmcintyre** [comment]
Definitely. This change has been made and will be included in the Orchestrion update for 6.5.

**Comment by Almagests** [comment]
Thanks the quick feedback and all your hard work!
