### ISSUE TITLE
[Feature Request] Audio File Song Replacement

### ISSUE THREAD

**Issue by ThatsNotAName** [lmcintyre/OrchestrionPlugin#46]
Any possibility to replace songs with our own audio files on our PC? I've seen other plugins that let you use custom sounds from audio files but not sure how hard it would be to pull from an audio file and play that instead of the song that's replaced. I did this a lot in runelite to replace music, would be cool if there was some way in FFXIV. Anyways, thanks for the overall great plugin :)

**Comment by lmcintyre** [comment]
Hi! This won't be implemented. There are plugins that are meant to do this, like Penumbra.
