### ISSUE TITLE
Is there any way to add the pulse remixes?

### ISSUE THREAD

**Issue by CrownTheEnd** [lmcintyre/OrchestrionPlugin#5]
From what I've seen, I can't find them in the list of available songs.

**Comment by torchick11** [comment]
They aren't in the files of the game

**Comment by ArutanSipdrae** [comment]
> They aren't in the files of the game

How is that possible? Not all of them ar ein the game but those that are on the orchestrion must be somewhere

**Comment by lmcintyre** [comment]
This plugin does not play Orchestrion tracks. Support may not be added as it bypasses explicit paywalls SE has set forth with regards to in-game tracks.

**Comment by ArutanSipdrae** [comment]
What about only displaying unlocked tracks

**Comment by torchick11** [comment]
> What about only displaying unlocked tracks

That isn't possible to do.

**Comment by lmcintyre** [comment]
The plugin does not currently play Orchestrion tracks due to the research needed to do so. The research may never be done due to bypassing explicit paywalls SE has set forth with regards to in-game tracks.
