### ISSUE TITLE
Add ALL Pulse's remixes

### ISSUE THREAD

**Issue by Netskia** [lmcintyre/OrchestrionPlugin#65]
Hello,
Is it possible to add ALL Pulse's remixes into the plugin please? :3 I do possess the originals but I'd love to get "What Angel makes me (Pulse)" wherever I go! Or the Leviathan remix for some bosses. 
Thanks!
Netska

**Comment by lmcintyre** [comment]
The plugin does not play Orchestrion rolls. The only pulse remixes present in the plugin are the ones that play in Eureka Orthos. I have no control over what music the plugin can play.

**Comment by Netskia** [comment]
Gotcha. Thanks for the swift answer! And for the mod, highly appreciated <3
