### ISSUE TITLE
Feature Request: Karaoke

### ISSUE THREAD

**Issue by roycebautista** [lmcintyre/OrchestrionPlugin#69]
I want to see the lyrics to the duty song that is currently playing.

Example: https://www.youtube.com/watch?v=Bb_-bGLLhn0&ab_channel=hungrychad

It doesn't need to be exactly like that, the font size and style can be something like this:
![image](https://github.com/user-attachments/assets/5a6fbdc3-6944-41b0-b42a-b6bc41a7e5e9)

So that it appears to look like part of the game.

**Comment by lmcintyre** [comment]
Hi! This would be a lot of work and it's far out of the scope of the plugin. I am sorry but I won't be adding this.
