### ISSUE TITLE
Title screen music plays at the same time as Orchestrion plugin music

### ISSUE THREAD

**Issue by valarnin** [lmcintyre/OrchestrionPlugin#9]
The title screen music plays at the same time as the plugin's music selection. Just noticed today. Steps I took:

1. Log in to a character
2. Select a song to play on loop in Orchestrion plugin
3. Log out to title screen

Not sure whether it's better to override the title screen music, or mute/pause the plugin music, but both playing at the same time is probably not intended.

**Comment by lmcintyre** [comment]
This should be fixed starting with 1.8.4.0. Any Orchestrion-played songs will now stop when you log out.
